# Generated by Django 4.2.5 on 2023-09-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('profile', models.CharField(max_length=40)),
                ('profile_num', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=25)),
                ('position_width', models.FloatField()),
                ('position_long', models.FloatField()),
            ],
        ),
    ]
