# Generated by Django 4.2.5 on 2023-09-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='position_long',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='position_width',
        ),
        migrations.AddField(
            model_name='student_info',
            name='geoposition',
            field=models.CharField(default=(0, 0), max_length=20),
            preserve_default=False,
        ),
    ]
